// models.js — общий список моделей по категориям (Дроны / Самокаты)
// Используется в index.html (выбор модели при добавлении товара).

const MODELS_BY_CATEGORY = {
    'Дроны': [
        'DJI Mavic 3', 'DJI Mavic 3 Only Drone', 'DJI Mavic 3 Fly More Combo',
        'DJI Mavic 3 Cine', 'DJI Mavic 3 Cine Only Drone', 'DJI Mavic 3 Cine Premium Combo',
        'DJI Mavic 3 Classic', 'DJI Mavic 3 Classic Only Drone', 'DJI Mavic 3 Classic Fly More Combo',
        'DJI Mavic 3 Pro', 'DJI Mavic 3 Pro Only Drone', 'DJI Mavic 3 Pro Fly More Combo',
        'DJI Mavic 3 Pro Cine', 'DJI Mavic 3 Pro Cine Only Drone', 'DJI Mavic 3 Pro Cine Premium Combo',
        'DJI Mavic 3 Enterprise (M3E)', 'DJI Mavic 3 Enterprise Only Drone', 'DJI Mavic 3 Enterprise Fly More Combo',
        'DJI Mavic 3E', 'DJI Mavic 3E Only Drone', 'DJI Mavic 3E Fly More Combo',
        'DJI Mavic 3T', 'DJI Mavic 3T Only Drone', 'DJI Mavic 3T Fly More Combo',
        'DJI Mavic 3M', 'DJI Mavic 3M Only Drone', 'DJI Mavic 3M Fly More Combo',
        'DJI Mavic 2 Pro', 'DJI Mavic 2 Pro Only Drone', 'DJI Mavic 2 Pro Fly More Combo',
        'DJI Mavic 2 Zoom', 'DJI Mavic 2 Zoom Only Drone', 'DJI Mavic 2 Zoom Fly More Combo',
        'DJI Mavic Pro', 'DJI Mavic Pro Only Drone',
        'DJI Air 3S', 'DJI Air 3S Only Drone', 'DJI Air 3S Fly More Combo',
        'DJI Air 3', 'DJI Air 3 Only Drone', 'DJI Air 3 Fly More Combo',
        'DJI Air 2S', 'DJI Air 2S Only Drone', 'DJI Air 2S Fly More Combo',
        'DJI Air 2', 'DJI Air 2 Only Drone', 'DJI Air 2 Fly More Combo',
        'DJI Mini 5 Pro', 'DJI Mini 5 Pro Only Drone', 'DJI Mini 5 Pro Fly More Combo',
        'DJI Mini 4 Pro', 'DJI Mini 4 Pro Only Drone', 'DJI Mini 4 Pro Fly More Combo',
        'DJI Mini 4K', 'DJI Mini 4K Only Drone', 'DJI Mini 4K Fly More Combo',
        'DJI Mini 3 Pro', 'DJI Mini 3 Pro Only Drone', 'DJI Mini 3 Pro Fly More Combo',
        'DJI Mini 3', 'DJI Mini 3 Only Drone', 'DJI Mini 3 Fly More Combo',
        'DJI Mini 2 SE', 'DJI Mini 2 SE Only Drone', 'DJI Mini 2 SE Fly More Combo',
        'DJI Mini 2', 'DJI Mini 2 Only Drone', 'DJI Mini 2 Fly More Combo',
        'DJI Mini SE', 'DJI Mini SE Only Drone',
        'DJI Neo 2', 'DJI Neo 2 Only Drone', 'DJI Neo 2 Fly More Combo',
        'DJI Neo', 'DJI Neo Only Drone', 'DJI Neo Fly More Combo', 'DJI Neo Motion Fly More Combo',
        'DJI Flip', 'DJI Flip Only Drone', 'DJI Flip Fly More Combo',
        'DJI Avata 2', 'DJI Avata 2 Only Drone', 'DJI Avata 2 Fly More Combo',
        'DJI Avata', 'DJI Avata Only Drone', 'DJI Avata Fly More Combo',
        'DJI Inspire 3', 'DJI Inspire 3 Only Drone', 'DJI Inspire 3 Premium Combo',
        'DJI Inspire 2', 'DJI Inspire 2 Only Drone', 'DJI Inspire 2 Fly More Combo',
        'DJI Matrice 350 RTK', 'DJI Matrice 350 RTK Only Drone', 'DJI Matrice 350 RTK Combo',
        'DJI Matrice 30', 'DJI Matrice 30 Only Drone', 'DJI Matrice 30 Combo',
        'DJI Matrice 30T', 'DJI Matrice 30T Only Drone', 'DJI Matrice 30T Combo',
        'DJI Matrice 300 RTK', 'DJI Matrice 300 RTK Only Drone', 'DJI Matrice 300 RTK Combo'
    ],
    'Самокаты': [
        'Xiaomi M365', 'Xiaomi M365 Pro', 'Xiaomi Mi Electric Scooter 1S',
        'Xiaomi Mi Electric Scooter Essential', 'Xiaomi Mi Electric Scooter Pro 2',
        'Xiaomi Mi Electric Scooter 3', 'Xiaomi Mi Electric Scooter 3 Lite',
        'Xiaomi Electric Scooter 4', 'Xiaomi Electric Scooter 4 Lite',
        'Xiaomi Electric Scooter 4 Pro', 'Xiaomi Electric Scooter 4 Ultra',
        'Xiaomi Electric Scooter 5', 'Xiaomi Electric Scooter 5 Pro',
        'Xiaomi Electric Scooter 5 Max', 'Xiaomi Electric Scooter 6 Ultra',
        'Ninebot ES1', 'Ninebot ES2', 'Ninebot ES4',
        'Ninebot Max G30', 'Ninebot Max G30LP', 'Ninebot Max G2', 'Ninebot Max G3',
        'Ninebot F20', 'Ninebot F25', 'Ninebot F30', 'Ninebot F40',
        'Ninebot F2', 'Ninebot F2 Pro', 'Ninebot F3', 'Ninebot F4',
        'Ninebot E22', 'Ninebot E25', 'Ninebot E45',
        'Segway D18E', 'Segway D28E', 'Segway D38E',
        'Segway P65E', 'Segway P100SE',
        'Segway GT1', 'Segway GT2', 'Segway GT3', 'Segway ZT3 Pro', 'Segway Air T15E',
        'NIU KQi1 Sport', 'NIU KQi2 Pro', 'NIU KQi3 Sport', 'NIU KQi3 Pro', 'NIU KQi3 Max',
        'NIU KQi 100P', 'NIU KQi 300X',
        'Navee N20', 'Navee N40', 'Navee N65', 'Navee S65', 'Navee V40', 'Navee UT5', 'Navee UT5 Ultra',
        'Hiboy S2', 'Hiboy S2 Pro', 'Hiboy KS4', 'Hiboy MAX3', 'Hiboy Titan',
        'Razor E90', 'Razor E100', 'Razor E200', 'Razor E300', 'Razor Power Core E90', 'Razor EcoSmart',
        'Pure Air', 'Pure Air Pro', 'Pure Advance',
        'TurboAnt X7', 'TurboAnt X7 Pro', 'TurboAnt X7 Max',
        'Levy Electric Scooter', 'Levy Plus',
        'Apollo Air', 'Apollo Air Pro', 'Apollo City', 'Apollo Explore', 'Apollo Ghost', 'Apollo Phantom', 'Apollo Go',
        'Kaabo Skywalker 8', 'Kaabo Skywalker 10S', 'Kaabo Mantis 8', 'Kaabo Mantis 10',
        'Kaabo Mantis Pro', 'Kaabo Mantis King GT',
        'Kaabo Wolf Warrior', 'Kaabo Wolf King', 'Kaabo Wolf King GT', 'Kaabo Wolf King GTR',
        'Dualtron Mini', 'Dualtron Compact', 'Dualtron Spider', 'Dualtron Eagle', 'Dualtron Raptor',
        'Dualtron Victor', 'Dualtron Victor Limited', 'Dualtron Thunder', 'Dualtron Thunder 2', 'Dualtron Thunder 3',
        'Dualtron Storm', 'Dualtron Storm Limited', 'Dualtron Ultra', 'Dualtron X', 'Dualtron X2',
        'Dualtron Alien', 'Dualtron Dolphin', 'Dualtron Sonic',
        'Dualtron TOGO', 'Dualtron TOGO Plus', 'Dualtron TOGO Pro', 'Dualtron TOGO Max', 'Dualtron TOGO Limited',
        'VSETT 8', 'VSETT 8+', 'VSETT 9', 'VSETT 9+', 'VSETT 10+', 'VSETT 11+',
        'INOKIM Light', 'INOKIM Quick', 'INOKIM OX', 'INOKIM OXO',
        'EMOVE Touring', 'EMOVE Cruiser',
        'Zero 8', 'Zero 9', 'Zero 10', 'Zero 10X', 'Zero 11X',
        'Kugoo S1', 'Kugoo S3', 'Kugoo G2 Pro', 'KuKirin G3', 'KuKirin G3 Pro',
        'GOTRAX GXL', 'GOTRAX G3', 'GOTRAX G4', 'GOTRAX GX1',
        'NanRobot D4+', 'NanRobot LS7', 'InMotion S1', 'InMotion L9',
        'E-TWOW Booster S', 'E-TWOW GT', 'Glion Dolly', 'Unagi Model One', 'Unagi Model One Voyager',
        'Swagtron Swagger', 'Mercane WideWheel', 'Splach Twin', 'Yume X11',
        'RION RE90', 'WEPED FS', 'NAMI Burn-E', 'NAMI Burn-E 2', 'NAMI Burn-E 2 Max',
        'Syccyba Atlant', 'Syccyba Flash Mono', 'Syccyba Gepard', 'Syccyba Gepard 6.0',
        'Syccyba Gepard 7.0', 'Syccyba Goliaf', 'Syccyba Hunter', 'Syccyba M10',
        'Syccyba M10 Lite', 'Syccyba Mangust', 'Syccyba Mangust 2.0', 'Syccyba Pantera',
        'Syccyba Pantera 2.0', 'Syccyba Pantera 3.0', 'Syccyba R11 Mini', 'Syccyba R11 Pro',
        'Syccyba R12', 'Syccyba R12 Pro', 'Syccyba R14', 'Syccyba R14 Pro', 'Syccyba R14 Lux',
        'Syccyba T100', 'Syccyba T1000', 'Syccyba H1 Dual', 'Syccyba H2', 'Syccyba H2 Dual',
        'Syccyba Impulse', 'Syccyba Impulse 5.0 Dual', 'Syccyba Impulse 6.0',
        'Syccyba Impulse X20', 'Syccyba Impulse X20 Lite', 'Syccyba Impulse X20 Dual',
        'Syccyba Impulse X21', 'Syccyba Impulse X21 Pro', 'Syccyba Impulse X21 Sport',
        'Syccyba Monster', 'Syccyba X22'
    ]
};
